if(NOT DEFINED CASE OR NOT DEFINED BIN OR NOT DEFINED SRC OR NOT DEFINED WORK)
	message(FATAL_ERROR "usage: cmake -DCASE=<name> -DBIN=<yirang-onnx> -DSRC=<examples dir> -DWORK=<work dir> -P cli_smoke.cmake")
endif()

set(case_dir ${WORK}/${CASE})
file(REMOVE_RECURSE ${case_dir})
file(MAKE_DIRECTORY ${case_dir})
file(COPY ${SRC}/models ${SRC}/tensors DESTINATION ${case_dir})
file(COPY ${SRC}/job_auto.json ${SRC}/job_bench.json ${SRC}/job_path.json ${SRC}/job_seed.json DESTINATION ${case_dir})

function(run_cli expected_code)
	execute_process(
		COMMAND ${BIN} ${ARGN}
		WORKING_DIRECTORY ${case_dir}
		RESULT_VARIABLE code
		OUTPUT_VARIABLE out
		ERROR_VARIABLE err)
	set(cli_output "${out}${err}" PARENT_SCOPE)
	if(NOT code EQUAL ${expected_code})
		message(FATAL_ERROR "[${CASE}] expected exit ${expected_code}, got '${code}'\n${out}${err}")
	endif()
endfunction()

function(expect_match pattern)
	if(NOT cli_output MATCHES "${pattern}")
		message(FATAL_ERROR "[${CASE}] output does not match '${pattern}'\n${cli_output}")
	endif()
endfunction()

function(expect_file path)
	if(NOT EXISTS ${case_dir}/${path})
		message(FATAL_ERROR "[${CASE}] expected file '${path}' was not created")
	endif()
endfunction()

if(CASE STREQUAL "help")
	run_cli(0 --help)
	expect_match("usage:")
elseif(CASE STREQUAL "version")
	run_cli(0 --version)
	expect_match("yirang-onnx [0-9]+\\.[0-9]+\\.[0-9]+")
elseif(CASE STREQUAL "no_args")
	run_cli(2)
	expect_match("invalid configuration")
elseif(CASE STREQUAL "summary")
	run_cli(0 --model models/linear.onnx)
	expect_match("operators")
	expect_match("Gemm")
elseif(CASE STREQUAL "job_auto")
	run_cli(0 --input-script job_auto.json)
	expect_match("saved")
	expect_file(outputs/output.pb)
elseif(CASE STREQUAL "job_dump_json")
	run_cli(0 --input-script job_path.json)
	expect_file(outputs/output.pb)
	expect_file(outputs/output.json)
elseif(CASE STREQUAL "job_benchmark")
	run_cli(0 --input-script job_bench.json)
	expect_match("runs \\(\\+10 warmup\\)")
elseif(CASE STREQUAL "unknown_key")
	file(WRITE ${case_dir}/bad_key.json "{ \"modl\": \"models/linear.onnx\" }")
	run_cli(2 --input-script bad_key.json)
	expect_match("unknown key")
elseif(CASE STREQUAL "malformed_script")
	file(WRITE ${case_dir}/broken.json "{ not json")
	run_cli(2 --input-script broken.json)
elseif(CASE STREQUAL "script_priority")
	run_cli(0 --input-script job_auto.json --model nonexistent.onnx)
	expect_file(outputs/output.pb)
elseif(CASE STREQUAL "outdir_supplement")
	file(WRITE ${case_dir}/job_no_outdir.json
		"{ \"model\": \"models/linear.onnx\", \"dim_overrides\": { \"N\": 1 }, \"run\": { \"repeat\": 1 }, \"outputs\": { \"save\": true } }")
	run_cli(0 --input-script job_no_outdir.json --out-dir custom_out)
	expect_file(custom_out/output.pb)
elseif(CASE STREQUAL "missing_model")
	run_cli(1 --model nonexistent.onnx)
elseif(CASE STREQUAL "cli_infer")
	run_cli(0 --model models/linear.onnx --input tensors/input.pb --out-dir cli_out)
	expect_file(cli_out/output.pb)
elseif(CASE STREQUAL "unknown_flag")
	run_cli(2 --model models/linear.onnx --wieghts true)
	expect_match("unknown argument")
elseif(CASE STREQUAL "script_relative_paths")
	file(MAKE_DIRECTORY ${case_dir}/nested)
	file(COPY ${SRC}/models DESTINATION ${case_dir}/nested)
	file(WRITE ${case_dir}/nested/job.json
		"{ \"model\": \"models/linear.onnx\", \"dim_overrides\": { \"N\": 1 }, \"run\": { \"repeat\": 1 }, \"outputs\": { \"dir\": \"out\", \"save\": true } }")
	# Run from case_dir (NOT nested/); model + output must resolve relative to the script's directory.
	run_cli(0 --input-script nested/job.json)
	expect_file(nested/out/output.pb)
else()
	message(FATAL_ERROR "unknown CASE '${CASE}'")
endif()
